version: '3'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paperless-backend-api
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
